baseURL = 'https://blog.orangeqwq.top'
languageCode = 'en-zh'
title = 'BigOrangeQWQ Blog'
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
cleanDestinationDir = true
theme = "smol"

[languages]
[languages.zh]
languageCode = "zh-CN"
languageName = "中文"
weight = 1

[languages.en]
languageCode = "en-US"
languageName = "English"
weight = 2

[menu]
# HEADER
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 3

# FOOTER
[[menu.footer]]
name = "Github"
url = "https://github.com/bigorangeqwq"
weight = 1
